services:
  app:
    image: lab10-notepad:latest
    build: .
    container_name: lab10-notepad-app
    ports:
      - "8082:8082"
    environment:
      - DB_URL=jdbc:sqlite:lab10.db
    volumes:
      - lab10_db_data:/data
    restart: unless-stopped

volumes:
  lab10_db_data:
